void handle_main()
{
  String page = "<!DOCTYPE HTML><html>";
  page+="<head>";
  page+="<title>Панель управления RGB кольцом</title>";
  page+="<meta name='viewport' content='width=device-width, initial-scale=1'>";
  page+="<meta charset='UTF-8'>";
  page+="<style>";
  page+=".headerblock {";
  page+="display: flex;";
  page+="flex-direction: column;";
  page+="align-items: center;";
  page+="justify-content: center;";
  page+="}";
  page+=".main {";
  page+="width: 50%;";
  page+="background: Palegoldenrod;";
  page+="}";
  page+="";
  page+="</style>";
  page+="</head>";
  page+="<body>";
  page+="<h1 align='center'>Панель управления RGB кольцом</h1>";
  page+="<div class='headerblock'>";
  page+="<h2>Выбор эффекта</h2>";
  page+="<div class='main'>";
  page+="<select name='efnum' id='efnum' width='80%' align='center'>";
  page+="<option value='1'>Выбор одного цвета</option>";
  page+="<option value='2'>Плавная смена цветов всей ленты</option>";
  page+="<option value='3'>Крутящаяся радуга</option>";
  page+="<option value='4'>случайная смена цветов</option>";
  page+="<option value='5'>Бегающий светодиод</option>";
  page+="<option value='6'>Бегающий паровозик светодиодов</option>";
  page+="<option value='7'>Вращаются красный и синий</option>";
  page+="<option value='8'>Вращается половина красных и половина синих</option>";
  page+="<option value='9'>Случайный стробоскоп</option>";
  page+="<option value='10'>Пульсация одним цветом</option>";
  page+="<option value='11'>Пульсация со сменой цветов</option>";
  page+=" <option value='12'>Плавная смена яркости</option>";
  page+="</select>";
  page+="</div></div>";
  page+="<div class='headerblock'>";
  page+="<h2>Настройка яркости</h2>";
  page+="<div class='main'>";
  page+="Установите с помощью слайдера яркость светодиодов</br>";
  page+="<input id='bright' type='range' min='0' max='255' step='1' width='100%' align='center' value='"+String(led_bright)+"'>";
  page+="</div></div>";
  page+="</body>";
  page+="</html>";
server.send(200, "text/html", page); 
}